### ISSUE TITLE
Exercises 7: Collaborating: Syncing

### ISSUE THREAD

**Issue by duaneloh** [asawaric/Newbie#3]
Make them create a new branch in Exercise 7 before 7.1. Give this new branch an explicit name, not just <new_branch>....

Make them checkout the new branch, make some edits to a specific file on this new branch, and commit these changes. 

Then in 7.3, have them rebase these changes of the new branch onto the master

Again, the answers have to be explicit -- they must work when I type them into my terminal. 

In 7.4, are there already tags in my_local repo? Consider expanding the question: create tags, and just work with local repo. Optionally push these tags to remote repo if possible.

**Comment by asawaric** [comment]
Modified Exercise questions as suggested.
