### ISSUE TITLE
Exercises 8: Collaborating: Using branches

### ISSUE THREAD

**Issue by duaneloh** [asawaric/Newbie#4]
How many branches have been created by the time the user tries Exercise 8?

Most of your results will be null if no branches have been created. 

Consider adding additional exercises to create one or two branches in Exercise 8, modifying each branch differently, before executing the commands in 8.1-8.3. 

Again, 8.2 and 8.3 are still vague --- be specific about the new_branch names.

**Comment by asawaric** [comment]
Modified Exercise questions as suggested.
