### ISSUE TITLE
Exercise 6.2

### ISSUE THREAD

**Issue by duaneloh** [asawaric/Newbie#5]
Create a new branch, edit a file and commit these changes on this new branch. 
Following this, edit a second file in the master branch, commit these changes. 
Then, rebase the new branch on the changes made on master, then merge these back into the master.
Try to depict this with an ASCII version of the branching tree listed in https://git-scm.com/book/en/v2/Git-Branching-Rebasing.
# Before rebasing

master: ____ A ___C
branch: ..........\ ____B
# After rebasing

master: ____ A ___C
branch: ................... \ ____B

**Comment by asawaric** [comment]
Modified Exercise questions as suggested.
